// Copyright 2020 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: uri/uri.proto

package uri

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Scheme is the generic URI syntax scheme.
// (-- api-linter: core::0126::upper-snake-values=disabled --)
type Scheme int32

const (
	// Conventional default for enums. Do not use this.
	Scheme_SCHEME_UNSPECIFIED Scheme = 0
	// File schema of filesystem path.
	Scheme_file Scheme = 1
	// HTTP schema of http.
	Scheme_http Scheme = 2
	// HTTPS schema of https.
	Scheme_https Scheme = 3
)

// Enum value maps for Scheme.
var (
	Scheme_name = map[int32]string{
		0: "SCHEME_UNSPECIFIED",
		1: "file",
		2: "http",
		3: "https",
	}
	Scheme_value = map[string]int32{
		"SCHEME_UNSPECIFIED": 0,
		"file":               1,
		"http":               2,
		"https":              3,
	}
)

func (x Scheme) Enum() *Scheme {
	p := new(Scheme)
	*p = x
	return p
}

func (x Scheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scheme) Descriptor() protoreflect.EnumDescriptor {
	return file_uri_uri_proto_enumTypes[0].Descriptor()
}

func (Scheme) Type() protoreflect.EnumType {
	return &file_uri_uri_proto_enumTypes[0]
}

func (x Scheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scheme.Descriptor instead.
func (Scheme) EnumDescriptor() ([]byte, []int) {
	return file_uri_uri_proto_rawDescGZIP(), []int{0}
}

// URI Uniform Resource Identifier (URI) https://tools.ietf.org/html/rfc3986.
//
// This class is a simple parser which creates the basic component parts
// (http://tools.ietf.org/html/rfc3986#section-3) with minimal validation
// and encoding.
//
//        foo://example.com:8042/over/there?name=ferret#nose
//        \_/   \______________/\_________/ \_________/ \__/
//         |           |            |            |        |
//      scheme     authority       path        query   fragment
//         |   _____________________|__
//        / \ /                        \
//        urn:example:animal:ferret:nose
type URI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *URI) Reset() {
	*x = URI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uri_uri_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URI) ProtoMessage() {}

func (x *URI) ProtoReflect() protoreflect.Message {
	mi := &file_uri_uri_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URI.ProtoReflect.Descriptor instead.
func (*URI) Descriptor() ([]byte, []int) {
	return file_uri_uri_proto_rawDescGZIP(), []int{0}
}

func (x *URI) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

var File_uri_uri_proto protoreflect.FileDescriptor

var file_uri_uri_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x72, 0x69, 0x2f, 0x75, 0x72, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x75, 0x72, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x03, 0x55, 0x52, 0x49, 0x12, 0x15, 0x0a, 0x03,
	0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x2a, 0x3f, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x12, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x68, 0x74, 0x74,
	0x70, 0x73, 0x10, 0x03, 0x42, 0x50, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x73, 0x70, 0x2e,
	0x75, 0x72, 0x69, 0x42, 0x08, 0x55, 0x72, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x12, 0x67, 0x6f, 0x2e, 0x6c, 0x73, 0x70, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x75, 0x72, 0x69, 0xf8, 0x01, 0x01, 0xa2, 0x02, 0x04, 0x4c, 0x53, 0x50, 0x55, 0xaa, 0x02, 0x03,
	0x55, 0x72, 0x69, 0xba, 0x02, 0x04, 0x4c, 0x53, 0x50, 0x55, 0xca, 0x02, 0x03, 0x55, 0x72, 0x69,
	0xea, 0x02, 0x03, 0x55, 0x72, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uri_uri_proto_rawDescOnce sync.Once
	file_uri_uri_proto_rawDescData = file_uri_uri_proto_rawDesc
)

func file_uri_uri_proto_rawDescGZIP() []byte {
	file_uri_uri_proto_rawDescOnce.Do(func() {
		file_uri_uri_proto_rawDescData = protoimpl.X.CompressGZIP(file_uri_uri_proto_rawDescData)
	})
	return file_uri_uri_proto_rawDescData
}

var (
	file_uri_uri_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_uri_uri_proto_msgTypes  = make([]protoimpl.MessageInfo, 1)
	file_uri_uri_proto_goTypes   = []interface{}{
		(Scheme)(0), // 0: uri.Scheme
		(*URI)(nil), // 1: uri.URI
	}
)

var file_uri_uri_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uri_uri_proto_init() }
func file_uri_uri_proto_init() {
	if File_uri_uri_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uri_uri_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uri_uri_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uri_uri_proto_goTypes,
		DependencyIndexes: file_uri_uri_proto_depIdxs,
		EnumInfos:         file_uri_uri_proto_enumTypes,
		MessageInfos:      file_uri_uri_proto_msgTypes,
	}.Build()
	File_uri_uri_proto = out.File
	file_uri_uri_proto_rawDesc = nil
	file_uri_uri_proto_goTypes = nil
	file_uri_uri_proto_depIdxs = nil
}
